In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [2]:
#sending request to web page
url= "https://www.imdb.com/list/ls095964455/"
page=requests.get(url)

In [3]:
soup=BeautifulSoup(page.content)

In [4]:
name=soup.find_all('h3', class_="lister-item-header")
tvshow_name=[]
for i in name:
    for j in i.find_all("a"):
        tvshow_name.append(j.text)
    
tvshow_name

['Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'La casa de papel',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters: The Mortal Instruments',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Élite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House M.D.',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 'Legends of Tomorrow',
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream',
 'The Haunting of Hill House']

In [5]:
year=soup.find_all('span', class_="lister-item-year text-muted unbold")
span_year=[]
for i in year:
    span_year.append(i.text)
    
    
    
    
span_year

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014– )',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011– )',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016– )',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2013)',
 '(2015– )',
 '(1999– )',
 '(2013– )',
 '(2004–2010)',
 '(2013– )',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016– )',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2021)',
 '(2013–2015)',
 '(2019– )',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015– )',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017– )',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005–2020)',
 '(2015–2019)',
 '(2018)']

In [6]:
genre=soup.find_all('span', class_="genre")
tvshow_genre=[]
for i in genre:
      tvshow_genre.append(i.text.replace("\n",''))
  
    
tvshow_genre

['Action, Adventure, Drama            ',
 'Drama, Fantasy, Horror            ',
 'Drama, Horror, Thriller            ',
 'Drama, Mystery, Thriller            ',
 'Drama, Mystery, Sci-Fi            ',
 'Comedy, Crime, Drama            ',
 'Crime, Drama, Mystery            ',
 'Drama, Romance            ',
 'Action, Adventure, Drama            ',
 'Action, Adventure, Crime            ',
 'Action, Crime, Mystery            ',
 'Comedy, Romance            ',
 'Drama, Sci-Fi, Thriller            ',
 'Crime, Drama, Mystery            ',
 'Action, Adventure, Drama            ',
 'Drama, Mystery, Romance            ',
 'Drama, Fantasy, Horror            ',
 'Drama, Horror, Thriller            ',
 'Crime, Drama, Thriller            ',
 'Crime, Drama, Fantasy            ',
 'Drama, Fantasy, Horror            ',
 'Action, Crime, Drama            ',
 'Crime, Drama, Mystery            ',
 'Action, Drama, Fantasy            ',
 'Animation, Comedy            ',
 'Adventure, Fantasy, Romance            ',
 'Biography, Crime, Drama            ',
 'Action, Crime, Drama            ',
 'Comedy, Romance            ',
 'Comedy, Romance            ',
 'Comedy, Drama            ',
 'Crime, Drama, Thriller            ',
 'Drama, Fantasy, Horror            ',
 'Action, Adventure, Drama            ',
 'Drama, Romance            ',
 'Drama, Mystery, Sci-Fi            ',
 'Action, Crime, Drama            ',
 'Drama, Mystery, Sci-Fi            ',
 'Action, Crime, Drama            ',
 'Comedy, Drama, Romance            ',
 'Animation, Adventure, Comedy            ',
 'Action, Drama, Fantasy            ',
 'Adventure, Comedy, Crime            ',
 'Drama            ',
 'Crime, Drama, Mystery            ',
 'Crime, Drama, Thriller            ',
 'Comedy, Drama            ',
 'Comedy, Drama            ',
 'Comedy            ',
 'Action, Adventure, Drama            ',
 'Crime, Drama, Romance            ',
 'Crime, Drama, Mystery            ',
 'Drama, Horror, Sci-Fi            ',
 'Animation, Comedy            ',
 'Crime, Drama, Mystery            ',
 'Adventure, Drama, Fantasy            ',
 'Crime, Drama            ',
 'Drama, Mystery            ',
 'Crime, Drama, Mystery            ',
 'Action, Drama, Sci-Fi            ',
 'Crime, Drama, Mystery            ',
 'Action, Crime, Drama            ',
 'Action, Adventure, Drama            ',
 'Drama, Sci-Fi, Thriller            ',
 'Drama, Fantasy, Horror            ',
 'Drama            ',
 'Comedy            ',
 'Comedy, Drama, Music            ',
 'Animation, Comedy            ',
 'Comedy, Crime            ',
 'Drama, Mystery, Sci-Fi            ',
 'Action, Adventure, Comedy            ',
 'Crime, Drama, Mystery            ',
 'Drama, Fantasy, Mystery            ',
 'Comedy, Drama, Mystery            ',
 'Crime, Drama            ',
 'Drama, Horror, Mystery            ',
 'Action, Crime, Drama            ',
 'Comedy, Drama            ',
 'Drama            ',
 'Comedy, Drama, Romance            ',
 'Comedy, Drama, Fantasy            ',
 'Action, Adventure, Crime            ',
 'Drama, Sci-Fi, Thriller            ',
 'Crime, Drama, Thriller            ',
 'Drama, Mystery, Thriller            ',
 'Action, Crime, Drama            ',
 'Drama, Thriller            ',
 'Action, Adventure, Crime            ',
 'Crime, Drama, Mystery            ',
 'Comedy, Drama, Thriller            ',
 'Crime, Drama, Mystery            ',
 'Biography, Drama, History            ',
 'Drama, History, Thriller            ',
 'Comedy, Crime, Drama            ',
 'Drama, Fantasy            ',
 'Adventure, Comedy, Drama            ',
 'Crime, Drama, Mystery            ',
 'Comedy, Crime, Drama            ',
 'Drama, Horror, Mystery            ']

In [7]:
time=soup.find_all('span', class_="runtime")
run_time=[]
for i in time:
      run_time.append(i.text)
  
    
run_time

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [13]:
rating=soup.find_all('span', class_="ipl-rating-star__rating")
show_rating=[]
for i in range(0,len(rating),23):
    show_rating.append(rating[i])
    
show_rating

[<span class="ipl-rating-star__rating">9.2</span>,
 <span class="ipl-rating-star__rating">8.7</span>,
 <span class="ipl-rating-star__rating">8.2</span>,
 <span class="ipl-rating-star__rating">7.6</span>,
 <span class="ipl-rating-star__rating">7.6</span>,
 <span class="ipl-rating-star__rating">8</span>,
 <span class="ipl-rating-star__rating">6.8</span>,
 <span class="ipl-rating-star__rating">7.5</span>,
 <span class="ipl-rating-star__rating">7.6</span>,
 <span class="ipl-rating-star__rating">7.5</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">8.1</span>,
 <span class="ipl-rating-star__rating">8.8</span>,
 <span class="ipl-rating-star__rating">9.1</span>,
 <span class="ipl-rating-star__rating">8.5</span>,
 <span class="ipl-rating-star__rating">7.4</span>,
 <span class="ipl-rating-star__rating">7.7</span>,
 <span class="ipl-rating-star__rating">8</span>,
 <span class="ipl-rating-star__rating">9.4</span>,
 <span class="ipl-rating-star__rating">8.1</span>,
 <span class="ipl-rating-star__rating">8.4</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">8.1</span>,
 <span class="ipl-rating-star__rating">7.6</span>,
 <span class="ipl-rating-star__rating">8.6</span>,
 <span class="ipl-rating-star__rating">7.7</span>,
 <span class="ipl-rating-star__rating">8.8</span>,
 <span class="ipl-rating-star__rating">8.6</span>,
 <span class="ipl-rating-star__rating">8.9</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">8.4</span>,
 <span class="ipl-rating-star__rating">8.5</span>,
 <span class="ipl-rating-star__rating">8.2</span>,
 <span class="ipl-rating-star__rating">6.2</span>,
 <span class="ipl-rating-star__rating">7.4</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">7.8</span>,
 <span class="ipl-rating-star__rating">8.6</span>,
 <span class="ipl-rating-star__rating">7.9</span>,
 <span class="ipl-rating-star__rating">8.4</span>,
 <span class="ipl-rating-star__rating">9.2</span>,
 <span class="ipl-rating-star__rating">6.6</span>,
 <span class="ipl-rating-star__rating">8.1</span>,
 <span class="ipl-rating-star__rating">8.7</span>,
 <span class="ipl-rating-star__rating">8.8</span>,
 <span class="ipl-rating-star__rating">7.5</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">8.5</span>,
 <span class="ipl-rating-star__rating">7.7</span>,
 <span class="ipl-rating-star__rating">7.5</span>,
 <span class="ipl-rating-star__rating">7.7</span>,
 <span class="ipl-rating-star__rating">8.6</span>,
 <span class="ipl-rating-star__rating">6.9</span>,
 <span class="ipl-rating-star__rating">8.1</span>,
 <span class="ipl-rating-star__rating">8</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">8.8</span>,
 <span class="ipl-rating-star__rating">8.7</span>,
 <span class="ipl-rating-star__rating">6.7</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">7.4</span>,
 <span class="ipl-rating-star__rating">6.8</span>,
 <span class="ipl-rating-star__rating">8.4</span>,
 <span class="ipl-rating-star__rating">7.5</span>,
 <span class="ipl-rating-star__rating">8.1</span>,
 <span class="ipl-rating-star__rating">7.8</span>,
 <span class="ipl-rating-star__rating">6.7</span>,
 <span class="ipl-rating-star__rating">8.7</span>,
 <span class="ipl-rating-star__rating">8.4</span>,
 <span class="ipl-rating-star__rating">6.6</span>,
 <span class="ipl-rating-star__rating">8</span>,
 <span class="ipl-rating-star__rating">8.9</span>,
 <span class="ipl-rating-star__rating">7.8</span>,
 <span class="ipl-rating-star__rating">7.5</span>,
 <span class="ipl-rating-star__rating">8.8</span>,
 <span class="ipl-rating-star__rating">8.1</span>,
 <span class="ipl-rating-star__rating">8.5</span>,
 <span class="ipl-rating-star__rating">8.3</span>,
 <span class="ipl-rating-star__rating">7.3</span>,
 <span class="ipl-rating-star__rating">8.7</span>,
 <span class="ipl-rating-star__rating">8.2</span>,
 <span class="ipl-rating-star__rating">6.4</span>,
 <span class="ipl-rating-star__rating">6.3</span>,
 <span class="ipl-rating-star__rating">8.6</span>,
 <span class="ipl-rating-star__rating">7.8</span>,
 <span class="ipl-rating-star__rating">7.3</span>,
 <span class="ipl-rating-star__rating">7.7</span>,
 <span class="ipl-rating-star__rating">7.3</span>,
 <span class="ipl-rating-star__rating">8.5</span>,
 <span class="ipl-rating-star__rating">6.5</span>,
 <span class="ipl-rating-star__rating">8.1</span>,
 <span class="ipl-rating-star__rating">8.6</span>,
 <span class="ipl-rating-star__rating">9.4</span>,
 <span class="ipl-rating-star__rating">7.8</span>,
 <span class="ipl-rating-star__rating">7.5</span>,
 <span class="ipl-rating-star__rating">7.8</span>,
 <span class="ipl-rating-star__rating">8</span>,
 <span class="ipl-rating-star__rating">7.1</span>,
 <span class="ipl-rating-star__rating">8.6</span>]

In [24]:
vote=soup.find_all('p',class_="text-muted text-small")
show_vote=[]
for i in vote:
    show_vote.append(i.text.replace('\n',''))
        
  
    
show_vote

['A|57 min|Action, Adventure, Drama            ',
 '                Stars:Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey',
 'Votes:1,867,644',
 '15|51 min|Drama, Fantasy, Horror            ',
 '                Stars:Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
 'Votes:903,218',
 '18+|44 min|Drama, Horror, Thriller            ',
 '                Stars:Andrew Lincoln, Norman Reedus, Melissa McBride, Lauren Cohan',
 'Votes:894,653',
 '16+|60 min|Drama, Mystery, Thriller            ',
 '                Stars:Dylan Minnette, Katherine Langford, Christian Navarro, Alisha Boe',
 'Votes:269,252',
 'A|43 min|Drama, Mystery, Sci-Fi            ',
 '                Stars:Eliza Taylor, Bob Morley, Marie Avgeropoulos, Isaiah Washington',
 'Votes:229,525',
 '18+|59 min|Comedy, Crime, Drama            ',
 '                Stars:Taylor Schilling, Danielle Brooks, Taryn Manning, Emma Myles',
 'Votes:286,212',
 '13+|45 min|Crime, Drama, Mystery            ',
 '                Stars:K.J. Apa, Lili Reinhart, Camila Mendes, Cole Sprouse',
 'Votes:128,342',
 '15+|41 min|Drama, Romance            ',
 '                Stars:Ellen Pompeo, Chandra Wilson, James Pickens Jr., Justin Chambers',
 'Votes:269,775',
 '12+|43 min|Action, Adventure, Drama            ',
 '                Stars:Grant Gustin, Candice Patton, Danielle Panabaker, Carlos Valdes',
 'Votes:323,635',
 'A|42 min|Action, Adventure, Crime            ',
 '                Stars:Stephen Amell, Katie Cassidy, David Ramsey, Susanna Thompson',
 'Votes:416,715',
 '16+|70 min|Action, Crime, Mystery            ',
 '                Stars:Úrsula Corberó, Álvaro Morte, Itziar Ituño, Pedro Alonso',
 'Votes:371,132',
 'U|22 min|Comedy, Romance            ',
 '                Stars:Johnny Galecki, Jim Parsons, Kaley Cuoco, Simon Helberg',
 'Votes:748,491',
 'A|60 min|Drama, Sci-Fi, Thriller            ',
 '                Stars:Daniel Lapaine, Hannah John-Kamen, Michaela Coel, Beatrice Robertson-Jones',
 'Votes:475,778',
 'UA|88 min|Crime, Drama, Mystery            ',
 '                Stars:Benedict Cumberbatch, Martin Freeman, Una Stubbs, Rupert Graves',
 'Votes:847,175',
 'A|44 min|Action, Adventure, Drama            ',
 '                Stars:Katheryn Winnick, Gustaf Skarsgård, Alexander Ludwig, Georgia Hirst',
 'Votes:466,648',
 'A|44 min|Drama, Mystery, Romance            ',
 '                Stars:Troian Bellisario, Ashley Benson, Lucy Hale, Shay Mitchell',
 'Votes:156,976',
 '16+|43 min|Drama, Fantasy, Horror            ',
 '                Stars:Nina Dobrev, Paul Wesley, Ian Somerhalder, Kat Graham',
 'Votes:295,950',
 'A|60 min|Drama, Horror, Thriller            ',
 '                Stars:Lady Gaga, Kathy Bates, Angela Bassett, Sarah Paulson',
 'Votes:290,010',
 '18|49 min|Crime, Drama, Thriller            ',
 '                Stars:Bryan Cranston, Aaron Paul, Anna Gunn, Betsy Brandt',
 'Votes:1,573,644',
 '15|42 min|Crime, Drama, Fantasy            ',
 '                Stars:Tom Ellis, Lesley-Ann Brandt, Lauren German, D.B. Woodside',
 'Votes:271,415',
 '16+|44 min|Drama, Fantasy, Horror            ',
 '                Stars:Jared Padalecki, Jensen Ackles, Jim Beaver, Misha Collins',
 'Votes:407,453',
 'UA|44 min|Action, Crime, Drama            ',
 '                Stars:Dominic Purcell, Wentworth Miller, Amaury Nolasco, Robert Knepper',
 'Votes:496,369',
 '18+|43 min|Crime, Drama, Mystery            ',
 '                Stars:Viola Davis, Billy Brown, Jack Falahee, Aja Naomi King',
 'Votes:137,717',
 '18|41 min|Action, Drama, Fantasy            ',
 "                Stars:Tyler Posey, Holland Roden, Dylan O'Brien, Linden Ashby",
 'Votes:134,520',
 'U|22 min|Animation, Comedy            ',
 '                Stars:Dan Castellaneta, Nancy Cartwright, Harry Shearer, Julie Kavner',
 'Votes:378,820',
 '16+|60 min|Adventure, Fantasy, Romance            ',
 '                Stars:Ginnifer Goodwin, Jennifer Morrison, Lana Parrilla, Robert Carlyle',
 'Votes:213,759',
 'A|49 min|Biography, Crime, Drama            ',
 '                Stars:Pedro Pascal, Lizbeth Eden, Wagner Moura, Boyd Holbrook',
 'Votes:379,711',
 '18+|54 min|Action, Crime, Drama            ',
 "                Stars:Charlie Cox, Vincent D'Onofrio, Deborah Ann Woll, Elden Henson",
 'Votes:378,703',
 '13+|22 min|Comedy, Romance            ',
 '                Stars:Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc',
 'Votes:892,915',
 '15+|22 min|Comedy, Romance            ',
 '                Stars:Josh Radnor, Jason Segel, Cobie Smulders, Neil Patrick Harris',
 'Votes:629,382',
 '13+|44 min|Comedy, Drama            ',
 '                Stars:Gabriel Macht, Patrick J. Adams, Meghan Markle, Sarah Rafferty',
 'Votes:377,327',
 '16+|49 min|Crime, Drama, Thriller            ',
 '                Stars:Rami Malek, Christian Slater, Carly Chaikin, Martin Wallström',
 'Votes:349,412',
 '16+|45 min|Drama, Fantasy, Horror            ',
 '                Stars:Joseph Morgan, Daniel Gillies, Claire Holt, Phoebe Tonkin',
 'Votes:123,933',
 '12+|43 min|Action, Adventure, Drama            ',
 '                Stars:Melissa Benoist, Chyler Leigh, David Harewood, Mehcad Brooks',
 'Votes:116,445',
 '18|42 min|Drama, Romance            ',
 '                Stars:Blake Lively, Leighton Meester, Penn Badgley, Ed Westwick',
 'Votes:161,262',
 '18|60 min|Drama, Mystery, Sci-Fi            ',
 '                Stars:Bae Doona, Jamie Clayton, Tina Desai, Tuppence Middleton',
 'Votes:145,088',
 '18+|42 min|Action, Crime, Drama            ',
 '                Stars:Ben McKenzie, Jada Pinkett Smith, Donal Logue, Camren Bicondova',
 'Votes:217,851',
 'A|62 min|Drama, Mystery, Sci-Fi            ',
 '                Stars:Evan Rachel Wood, Jeffrey Wright, Ed Harris, Thandiwe Newton',
 'Votes:449,171',
 '18|56 min|Action, Crime, Drama            ',
 '                Stars:Krysten Ritter, Rachael Taylor, Eka Darville, Carrie-Anne Moss',
 'Votes:199,612',
 '12+|22 min|Comedy, Drama, Romance            ',
 "                Stars:Ed O'Neill, Sofía Vergara, Julie Bowen, Ty Burrell",
 'Votes:383,166',
 '16+|23 min|Animation, Adventure, Comedy            ',
 '                Stars:Justin Roiland, Chris Parnell, Spencer Grammer, Sarah Chalke',
 'Votes:426,537',
 '18|42 min|Action, Drama, Fantasy            ',
 '                Stars:Katherine McNamara, Dominic Sherwood, Alberto Rosende, Matthew Daddario',
 'Votes:56,943',
 '18+|25 min|Adventure, Comedy, Crime            ',
 '                Stars:Jessica Barden, Alex Lawther, Steve Oram, Christine Bottomley',
 'Votes:160,869',
 '16+|51 min|Drama            ',
 '                Stars:Kevin Spacey, Michel Gill, Robin Wright, Kate Mara',
 'Votes:479,489',
 '16+|60 min|Crime, Drama, Mystery            ',
 '                Stars:Louis Hofmann, Karoline Eichhorn, Lisa Vicari, Maja Schöne',
 'Votes:319,188',
 '18+|60 min|Crime, Drama, Thriller            ',
 '                Stars:Itzan Escamilla, Omar Ayuso, Miguel Bernardeau, Arón Piper',
 'Votes:61,957',
 'A|45 min|Comedy, Drama            ',
 '                Stars:Asa Butterfield, Gillian Anderson, Emma Mackey, Kedar Williams-Stirling',
 'Votes:182,235',
 '18+|46 min|Comedy, Drama            ',
 '                Stars:Emmy Rossum, William H. Macy, Ethan Cutkosky, Jeremy Allen White',
 'Votes:215,027',
 '15+|22 min|Comedy            ',
 '                Stars:Zooey Deschanel, Jake Johnson, Max Greenfield, Hannah Simone',
 'Votes:202,476',
 '16+|45 min|Action, Adventure, Drama            ',
 '                Stars:Clark Gregg, Ming-Na Wen, Brett Dalton, Iain De Caestecker',
 'Votes:206,519',
 '16+|45 min|Crime, Drama, Romance            ',
 '                Stars:Penn Badgley, Victoria Pedretti, Ambyr Childers, Elizabeth Lail',
 'Votes:161,294',
 'A|53 min|Crime, Drama, Mystery            ',
 '                Stars:Michael C. Hall, Jennifer Carpenter, David Zayas, James Remar',
 'Votes:671,910',
 '16+|44 min|Drama, Horror, Sci-Fi            ',
 '                Stars:Kim Dickens, Frank Dillane, Cliff Curtis, Rubén Blades',
 'Votes:119,007',
 '13|22 min|Animation, Comedy            ',
 '                Stars:Seth MacFarlane, Alex Borstein, Seth Green, Mila Kunis',
 'Votes:314,834',
 '16+|43 min|Crime, Drama, Mystery            ',
 '                Stars:James Spader, Megan Boone, Diego Klattenhoff, Ryan Eggold',
 'Votes:216,332',
 'A|44 min|Adventure, Drama, Fantasy            ',
 '                Stars:Jorge Garcia, Josh Holloway, Yunjin Kim, Evangeline Lilly',
 'Votes:516,336',
 'A|60 min|Crime, Drama            ',
 '                Stars:Cillian Murphy, Paul Anderson, Helen McCrory, Sophie Rundle',
 'Votes:404,103',
 'UA|44 min|Drama, Mystery            ',
 '                Stars:Hugh Laurie, Omar Epps, Robert Sean Leonard, Jesse Spencer',
 'Votes:429,129',
 '18|42 min|Crime, Drama, Mystery            ',
 '                Stars:Priyanka Chopra Jonas, Jake McLaughlin, Johanna Braddy, Aunjanue Ellis',
 'Votes:58,624',
 '18|44 min|Action, Drama, Sci-Fi            ',
 '                Stars:Tatiana Maslany, Dylan Bruce, Jordan Gavaris, Kevin Hanchard',
 'Votes:105,260',
 'UA|55 min|Crime, Drama, Mystery            ',
 '                Stars:Claire Danes, Mandy Patinkin, Damian Lewis, Rupert Friend',
 'Votes:324,139',
 '16|42 min|Action, Crime, Drama            ',
 '                Stars:Sullivan Stapleton, Jaimie Alexander, Audrey Esparza, Ashley Johnson',
 'Votes:68,973',
 'A|42 min|Action, Adventure, Drama            ',
 '                Stars:Caity Lotz, Amy Louise Pemberton, Dominic Purcell, Nick Zano',
 'Votes:97,032',
 'A|60 min|Drama, Sci-Fi, Thriller            ',
 '                Stars:Elisabeth Moss, Yvonne Strahovski, Joseph Fiennes, Ann Dowd',
 'Votes:200,310',
 '18|60 min|Drama, Fantasy, Horror            ',
 '                Stars:Kiernan Shipka, Ross Lynch, Lucy Davis, Chance Perdomo',
 'Votes:83,785',
 '15+|41 min|Drama            ',
 '                Stars:Freddie Highmore, Hill Harper, Richard Schiff, Antonia Thomas',
 'Votes:75,208',
 '18|60 min|Comedy            ',
 '                Stars:Gina Rodriguez, Andrea Navedo, Yael Grobglas, Justin Baldoni',
 'Votes:42,658',
 '18|44 min|Comedy, Drama, Music            ',
 '                Stars:Lea Michele, Jane Lynch, Matthew Morrison, Cory Monteith',
 'Votes:140,875',
 '18+|22 min|Animation, Comedy            ',
 '                Stars:Trey Parker, Matt Stone, Isaac Hayes, Mona Marshall',
 'Votes:343,002',
 '13+|22 min|Comedy, Crime            ',
 '                Stars:Andy Samberg, Stephanie Beatriz, Terry Crews, Melissa Fumero',
 'Votes:256,449',
 '43 min|Drama, Mystery, Sci-Fi            ',
 '                Stars:Mike Vogel, Rachelle Lefevre, Alexander Koch, Colin Ford',
 'Votes:103,212',
 '16+|60 min|Action, Adventure, Comedy            ',
 '                Stars:Elliot Page, Tom Hopper, David Castañeda, Emmy Raver-Lampman',
 'Votes:179,388',
 'A|55 min|Crime, Drama, Mystery            ',
 '                Stars:Vince Vaughn, Colin Farrell, Rachel McAdams, Taylor Kitsch',
 'Votes:520,296',
 'A|60 min|Drama, Fantasy, Mystery            ',
 '                Stars:Brit Marling, Jason Isaacs, Scott Wilson, Alice Krige',
 'Votes:96,112',
 '45 min|Comedy, Drama, Mystery            ',
 '                Stars:Teri Hatcher, Felicity Huffman, Marcia Cross, Eva Longoria',
 'Votes:120,725',
 '16+|46 min|Crime, Drama            ',
 '                Stars:Bob Odenkirk, Rhea Seehorn, Jonathan Banks, Patrick Fabian',
 'Votes:354,280',
 '16|45 min|Drama, Horror, Mystery            ',
 '                Stars:Vera Farmiga, Freddie Highmore, Max Thieriot, Nicola Peltz',
 'Votes:101,335',
 'A|53 min|Action, Crime, Drama            ',
 '                Stars:Jon Bernthal, Amber Rose Revah, Ben Barnes, Jason R. Moore',
 'Votes:197,859',
 '18|30 min|Comedy, Drama            ',
 '                Stars:Jennifer Jason Leigh, Keir Gilchrist, Brigette Lundy-Paine, Michael Rapaport',
 'Votes:75,263',
 '13|42 min|Drama            ',
 '                Stars:Elizabeth Gillies, Rafael de la Fuente, Robert Christopher Riley, Sam Adegoke',
 'Votes:17,097',
 '16|45 min|Comedy, Drama, Romance            ',
 '                Stars:Milo Ventimiglia, Mandy Moore, Sterling K. Brown, Chrissy Metz',
 'Votes:117,628',
 '13+|22 min|Comedy, Drama, Fantasy            ',
 "                Stars:Kristen Bell, William Jackson Harper, Jameela Jamil, D'Arcy Carden",
 'Votes:130,245',
 '16|55 min|Action, Adventure, Crime            ',
 '                Stars:Finn Jones, Jessica Henwick, Jessica Stroup, Tom Pelphrey',
 'Votes:120,105',
 '18|45 min|Drama, Sci-Fi, Thriller            ',
 '                Stars:Alba August, Lucas Lynggaard Tønnesen, Mikkel Boe Følsgaard, Lukas Løkken',
 'Votes:33,339',
 '16+|60 min|Crime, Drama, Thriller            ',
 '                Stars:Jonathan Groff, Holt McCallany, Anna Torv, Hannah Gross',
 'Votes:240,031',
 '44 min|Drama, Mystery, Thriller            ',
 '                Stars:Madeleine Stowe, Emily VanCamp, Gabriel Mann, Nick Wechsler',
 'Votes:115,594',
 '18|55 min|Action, Crime, Drama            ',
 '                Stars:Mike Colter, Simone Missick, Theo Rossi, Alfre Woodard',
 'Votes:121,192',
 'UA|43 min|Drama, Thriller            ',
 '                Stars:Kerry Washington, Darby Stanchfield, Katie Lowes, Guillermo Díaz',
 'Votes:69,328',
 '50 min|Action, Adventure, Crime            ',
 '                Stars:Charlie Cox, Krysten Ritter, Mike Colter, Finn Jones',
 'Votes:95,686',
 '15+|60 min|Crime, Drama, Mystery            ',
 '                Stars:Reese Witherspoon, Nicole Kidman, Shailene Woodley, Zoë Kravitz',
 'Votes:171,505',
 '18|45 min|Comedy, Drama, Thriller            ',
 '                Stars:Dallas Roberts, Debby Ryan, Christopher Gorham, Kimmy Shields',
 'Votes:24,755',
 '16+|43 min|Crime, Drama, Mystery            ',
 '                Stars:Simon Baker, Robin Tunney, Tim Kang, Owain Yeoman',
 'Votes:171,344',
 '16+|58 min|Biography, Drama, History            ',
 '                Stars:Claire Foy, Olivia Colman, Imelda Staunton, Matt Smith',
 'Votes:172,557',
 '330 min|Drama, History, Thriller            ',
 '                Stars:Jessie Buckley, Jared Harris, Stellan Skarsgård, Adam Nagaitis',
 'Votes:607,355',
 '18|42 min|Comedy, Crime, Drama            ',
 '                Stars:Rose McIver, Malcolm Goodwin, Rahul Kohli, Robert Buckley',
 'Votes:62,813',
 '16|42 min|Drama, Fantasy            ',
 '                Stars:Adelaide Kane, Megan Follows, Celina Sinden, Torrance Coombs',
 'Votes:45,488',
 '7|50 min|Adventure, Comedy, Drama            ',
 '                Stars:Neil Patrick Harris, Patrick Warburton, Malina Weissman, Louis Hynes',
 'Votes:56,362',
 '42 min|Crime, Drama, Mystery            ',
 '                Stars:Matthew Gray Gubler, Kirsten Vangsness, A.J. Cook, Joe Mantegna',
 'Votes:174,385',
 '18|45 min|Comedy, Crime, Drama            ',
 '                Stars:Willa Fitzgerald, Bex Taylor-Klaus, John Karna, Carlson Young',
 'Votes:36,491',
 '16+|572 min|Drama, Horror, Mystery            ',
 '                Stars:Michiel Huisman, Carla Gugino, Henry Thomas, Elizabeth Reaser',
 'Votes:198,232']

In [40]:
votes=[]
for i in range(2,len(show_vote),3):
    votes.append(show_vote[i])
votes

['Votes:1,867,644',
 'Votes:903,218',
 'Votes:894,653',
 'Votes:269,252',
 'Votes:229,525',
 'Votes:286,212',
 'Votes:128,342',
 'Votes:269,775',
 'Votes:323,635',
 'Votes:416,715',
 'Votes:371,132',
 'Votes:748,491',
 'Votes:475,778',
 'Votes:847,175',
 'Votes:466,648',
 'Votes:156,976',
 'Votes:295,950',
 'Votes:290,010',
 'Votes:1,573,644',
 'Votes:271,415',
 'Votes:407,453',
 'Votes:496,369',
 'Votes:137,717',
 'Votes:134,520',
 'Votes:378,820',
 'Votes:213,759',
 'Votes:379,711',
 'Votes:378,703',
 'Votes:892,915',
 'Votes:629,382',
 'Votes:377,327',
 'Votes:349,412',
 'Votes:123,933',
 'Votes:116,445',
 'Votes:161,262',
 'Votes:145,088',
 'Votes:217,851',
 'Votes:449,171',
 'Votes:199,612',
 'Votes:383,166',
 'Votes:426,537',
 'Votes:56,943',
 'Votes:160,869',
 'Votes:479,489',
 'Votes:319,188',
 'Votes:61,957',
 'Votes:182,235',
 'Votes:215,027',
 'Votes:202,476',
 'Votes:206,519',
 'Votes:161,294',
 'Votes:671,910',
 'Votes:119,007',
 'Votes:314,834',
 'Votes:216,332',
 'Votes:516,336',
 'Votes:404,103',
 'Votes:429,129',
 'Votes:58,624',
 'Votes:105,260',
 'Votes:324,139',
 'Votes:68,973',
 'Votes:97,032',
 'Votes:200,310',
 'Votes:83,785',
 'Votes:75,208',
 'Votes:42,658',
 'Votes:140,875',
 'Votes:343,002',
 'Votes:256,449',
 'Votes:103,212',
 'Votes:179,388',
 'Votes:520,296',
 'Votes:96,112',
 'Votes:120,725',
 'Votes:354,280',
 'Votes:101,335',
 'Votes:197,859',
 'Votes:75,263',
 'Votes:17,097',
 'Votes:117,628',
 'Votes:130,245',
 'Votes:120,105',
 'Votes:33,339',
 'Votes:240,031',
 'Votes:115,594',
 'Votes:121,192',
 'Votes:69,328',
 'Votes:95,686',
 'Votes:171,505',
 'Votes:24,755',
 'Votes:171,344',
 'Votes:172,557',
 'Votes:607,355',
 'Votes:62,813',
 'Votes:45,488',
 'Votes:56,362',
 'Votes:174,385',
 'Votes:36,491',
 'Votes:198,232']

In [50]:
print(len(votes),len(show_rating),len(run_time),len(tvshow_genre),len(span_year),len(tvshow_name))

100 100 100 100 100 100

In [51]:
mostwatched_tvseries=pd.DataFrame({})
mostwatched_tvseries['Show Name']=tvshow_name
mostwatched_tvseries['Year Span']=span_year
mostwatched_tvseries['Genre']=tvshow_genre
mostwatched_tvseries['Run Time']=run_time
mostwatched_tvseries['Ratings']=show_rating
mostwatched_tvseries['Show Vote']=votes
mostwatched_tvseries

,Show Name,Year Span,Genre,Run Time,Ratings,Show Vote
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,[9.2],"Votes:1,867,644"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,[8.7],"Votes:903,218"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,[8.2],"Votes:894,653"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,[7.6],"Votes:269,252"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,[7.6],"Votes:229,525"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,[7.5],"Votes:45,488"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,[7.8],"Votes:56,362"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,[8],"Votes:174,385"
98,Scream,(2015–2019),"Comedy, Crime, Drama",45 min,[7.1],"Votes:36,491"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,[8.6],"Votes:198,232"

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [27]:
url1='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
page1=requests.get(url1)
soup1=BeautifulSoup(page1.content)

In [32]:
book_title=soup1.find_all('td', class_="left")
titles=[]
for i in book_title:
    titles.append(i.text)
titles

[' 1 ',
 ' Da Vinci Code,The ',
 ' Brown, Dan ',
 ' 5,094,805 ',
 ' Transworld ',
 ' Crime, Thriller & Adventure ',
 ' 2 ',
 ' Harry Potter and the Deathly Hallows ',
 ' Rowling, J.K. ',
 ' 4,475,152 ',
 ' Bloomsbury ',
 " Children's Fiction ",
 ' 3 ',
 " Harry Potter and the Philosopher's Stone ",
 ' Rowling, J.K. ',
 ' 4,200,654 ',
 ' Bloomsbury ',
 " Children's Fiction ",
 ' 4 ',
 ' Harry Potter and the Order of the Phoenix ',
 ' Rowling, J.K. ',
 ' 4,179,479 ',
 ' Bloomsbury ',
 " Children's Fiction ",
 ' 5 ',
 ' Fifty Shades of Grey ',
 ' James, E. L. ',
 ' 3,758,936 ',
 ' Random House ',
 ' Romance & Sagas ',
 ' 6 ',
 ' Harry Potter and the Goblet of Fire ',
 ' Rowling, J.K. ',
 ' 3,583,215 ',
 ' Bloomsbury ',
 " Children's Fiction ",
 ' 7 ',
 ' Harry Potter and the Chamber of Secrets ',
 ' Rowling, J.K. ',
 ' 3,484,047 ',
 ' Bloomsbury ',
 " Children's Fiction ",
 ' 8 ',
 ' Harry Potter and the Prisoner of Azkaban ',
 ' Rowling, J.K. ',
 ' 3,377,906 ',
 ' Bloomsbury ',
 " Children's Fiction ",
 ' 9 ',
 ' Angels and Demons ',
 ' Brown, Dan ',
 ' 3,193,946 ',
 ' Transworld ',
 ' Crime, Thriller & Adventure ',
 ' 10 ',
 " Harry Potter and the Half-blood Prince:Children's Edition ",
 ' Rowling, J.K. ',
 ' 2,950,264 ',
 ' Bloomsbury ',
 " Children's Fiction ",
 ' 11 ',
 ' Fifty Shades Darker ',
 ' James, E. L. ',
 ' 2,479,784 ',
 ' Random House ',
 ' Romance & Sagas ',
 ' 12 ',
 ' Twilight ',
 ' Meyer, Stephenie ',
 ' 2,315,405 ',
 ' Little, Brown Book ',
 ' Young Adult Fiction ',
 ' 13 ',
 ' Girl with the Dragon Tattoo,The:Millennium Trilogy ',
 ' Larsson, Stieg ',
 ' 2,233,570 ',
 ' Quercus ',
 ' Crime, Thriller & Adventure ',
 ' 14 ',
 ' Fifty Shades Freed ',
 ' James, E. L. ',
 ' 2,193,928 ',
 ' Random House ',
 ' Romance & Sagas ',
 ' 15 ',
 ' Lost Symbol,The ',
 ' Brown, Dan ',
 ' 2,183,031 ',
 ' Transworld ',
 ' Crime, Thriller & Adventure ',
 ' 16 ',
 ' New Moon ',
 ' Meyer, Stephenie ',
 ' 2,152,737 ',
 ' Little, Brown Book ',
 ' Young Adult Fiction ',
 ' 17 ',
 ' Deception Point ',
 ' Brown, Dan ',
 ' 2,062,145 ',
 ' Transworld ',
 ' Crime, Thriller & Adventure ',
 ' 18 ',
 ' Eclipse ',
 ' Meyer, Stephenie ',
 ' 2,052,876 ',
 ' Little, Brown Book ',
 ' Young Adult Fiction ',
 ' 19 ',
 ' Lovely Bones,The ',
 ' Sebold, Alice ',
 ' 2,005,598 ',
 ' Pan Macmillan ',
 ' General & Literary Fiction ',
 ' 20 ',
 ' Curious Incident of the Dog in the Night-time,The ',
 ' Haddon, Mark ',
 ' 1,979,552 ',
 ' Random House ',
 ' General & Literary Fiction ',
 ' 21 ',
 ' Digital Fortress ',
 ' Brown, Dan ',
 ' 1,928,900 ',
 ' Transworld ',
 ' Crime, Thriller & Adventure ',
 ' 22 ',
 ' Short History of Nearly Everything,A ',
 ' Bryson, Bill ',
 ' 1,852,919 ',
 ' Transworld ',
 ' Popular Science ',
 ' 23 ',
 ' Girl Who Played with Fire,The:Millennium Trilogy ',
 ' Larsson, Stieg ',
 ' 1,814,784 ',
 ' Quercus ',
 ' Crime, Thriller & Adventure ',
 ' 24 ',
 ' Breaking Dawn ',
 ' Meyer, Stephenie ',
 ' 1,787,118 ',
 ' Little, Brown Book ',
 ' Young Adult Fiction ',
 ' 25 ',
 ' Very Hungry Caterpillar,The:The Very Hungry Caterpillar ',
 ' Carle, Eric ',
 ' 1,783,535 ',
 ' Penguin ',
 ' Picture Books ',
 ' 26 ',
 ' Gruffalo,The ',
 ' Donaldson, Julia ',
 ' 1,781,269 ',
 ' Pan Macmillan ',
 ' Picture Books ',
 ' 27 ',
 " Jamie's 30-Minute Meals ",
 ' Oliver, Jamie ',
 ' 1,743,266 ',
 ' Penguin ',
 ' Food & Drink: General ',
 ' 28 ',
 ' Kite Runner,The ',
 ' Hosseini, Khaled ',
 ' 1,629,119 ',
 ' Bloomsbury ',
 ' General & Literary Fiction ',
 ' 29 ',
 ' One Day ',
 ' Nicholls, David ',
 ' 1,616,068 ',
 ' Hodder & Stoughton ',
 ' General & Literary Fiction ',
 ' 30 ',
 ' Thousand Splendid Suns,A ',
 ' Hosseini, Khaled ',
 ' 1,583,992 ',
 ' Bloomsbury ',
 ' General & Literary Fiction ',
 ' 31 ',
 " Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy ",
 ' Larsson, Stieg ',
 ' 1,555,135 ',
 ' Quercus ',
 ' Crime, Thriller & Adventure ',
 ' 32 ',
 " Time Traveler's Wife,The ",
 ' Niffenegger, Audrey ',
 ' 1,546,886 ',
 ' Random House ',
 ' General & Literary Fiction ',
 ' 33 ',
 ' Atonement ',
 ' McEwan, Ian ',
 ' 1,539,428 ',
 ' Random House ',
 ' General & Literary Fiction ',
 ' 34 ',
 " Bridget Jones's Diary:A Novel ",
 ' Fielding, Helen ',
 ' 1,508,205 ',
 ' Pan Macmillan ',
 ' General & Literary Fiction ',
 ' 35 ',
 ' World According to Clarkson,The ',
 ' Clarkson, Jeremy ',
 ' 1,489,403 ',
 ' Penguin ',
 ' Humour: Collections & General ',
 ' 36 ',
 " Captain Corelli's Mandolin ",
 ' Bernieres, Louis de ',
 ' 1,352,318 ',
 ' Random House ',
 ' General & Literary Fiction ',
 ' 37 ',
 ' Sound of Laughter,The ',
 ' Kay, Peter ',
 ' 1,310,207 ',
 ' Random House ',
 ' Autobiography: General ',
 ' 38 ',
 ' Life of Pi ',
 ' Martel, Yann ',
 ' 1,310,176 ',
 ' Canongate ',
 ' General & Literary Fiction ',
 ' 39 ',
 ' Billy Connolly ',
 ' Stephenson, Pamela ',
 ' 1,231,957 ',
 ' HarperCollins ',
 ' Biography: The Arts ',
 ' 40 ',
 ' Child Called It,A ',
 ' Pelzer, Dave ',
 ' 1,217,712 ',
 ' Orion ',
 ' Autobiography: General ',
 ' 41 ',
 " Gruffalo's Child,The ",
 ' Donaldson, Julia ',
 ' 1,208,711 ',
 ' Pan Macmillan ',
 ' Picture Books ',
 ' 42 ',
 " Angela's Ashes:A Memoir of a Childhood ",
 ' McCourt, Frank ',
 ' 1,204,058 ',
 ' HarperCollins ',
 ' Autobiography: General ',
 ' 43 ',
 ' Birdsong ',
 ' Faulks, Sebastian ',
 ' 1,184,967 ',
 ' Random House ',
 ' General & Literary Fiction ',
 ' 44 ',
 ' Northern Lights:His Dark Materials S. ',
 ' Pullman, Philip ',
 ' 1,181,503 ',
 ' Scholastic Ltd. ',
 ' Young Adult Fiction ',
 ' 45 ',
 ' Labyrinth ',
 ' Mosse, Kate ',
 ' 1,181,093 ',
 ' Orion ',
 ' General & Literary Fiction ',
 ' 46 ',
 ' Harry Potter and the Half-blood Prince ',
 ' Rowling, J.K. ',
 ' 1,153,181 ',
 ' Bloomsbury ',
 ' Science Fiction & Fantasy ',
 ' 47 ',
 ' Help,The ',
 ' Stockett, Kathryn ',
 ' 1,132,336 ',
 ' Penguin ',
 ' General & Literary Fiction ',
 ' 48 ',
 ' Man and Boy ',
 ' Parsons, Tony ',
 ' 1,130,802 ',
 ' HarperCollins ',
 ' General & Literary Fiction ',
 ' 49 ',
 ' Memoirs of a Geisha ',
 ' Golden, Arthur ',
 ' 1,126,337 ',
 ' Random House ',
 ' General & Literary Fiction ',
 ' 50 ',
 " No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S. ",
 ' McCall Smith, Alexander ',
 ' 1,115,549 ',
 ' Little, Brown Book ',
 ' Crime, Thriller & Adventure ',
 ' 51 ',
 ' Island,The ',
 ' Hislop, Victoria ',
 ' 1,108,328 ',
 ' Headline ',
 ' General & Literary Fiction ',
 ' 52 ',
 ' PS, I Love You ',
 ' Ahern, Cecelia ',
 ' 1,107,379 ',
 ' HarperCollins ',
 ' General & Literary Fiction ',
 ' 53 ',
 ' You are What You Eat:The Plan That Will Change Your Life ',
 ' McKeith, Gillian ',
 ' 1,104,403 ',
 ' Penguin ',
 ' Fitness & Diet ',
 ' 54 ',
 ' Shadow of the Wind,The ',
 ' Zafon, Carlos Ruiz ',
 ' 1,092,349 ',
 ' Orion ',
 ' General & Literary Fiction ',
 ' 55 ',
 ' Tales of Beedle the Bard,The ',
 ' Rowling, J.K. ',
 ' 1,090,847 ',
 ' Bloomsbury ',
 " Children's Fiction ",
 ' 56 ',
 ' Broker,The ',
 ' Grisham, John ',
 ' 1,087,262 ',
 ' Random House ',
 ' Crime, Thriller & Adventure ',
 ' 57 ',
 " Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P ",
 ' Atkins, Robert C. ',
 ' 1,054,196 ',
 ' Random House ',
 ' Fitness & Diet ',
 ' 58 ',
 ' Subtle Knife,The:His Dark Materials S. ',
 ' Pullman, Philip ',
 ' 1,037,160 ',
 ' Scholastic Ltd. ',
 ' Young Adult Fiction ',
 ' 59 ',
 ' Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation ',
 ' Truss, Lynne ',
 ' 1,023,688 ',
 ' Profile Books Group ',
 ' Usage & Writing Guides ',
 ' 60 ',
 " Delia's How to Cook:(Bk.1) ",
 ' Smith, Delia ',
 ' 1,015,956 ',
 ' Random House ',
 ' Food & Drink: General ',
 ' 61 ',
 ' Chocolat ',
 ' Harris, Joanne ',
 ' 1,009,873 ',
 ' Transworld ',
 ' General & Literary Fiction ',
 ' 62 ',
 ' Boy in the Striped Pyjamas,The ',
 ' Boyne, John ',
 ' 1,004,414 ',
 ' Random House Childrens Books G ',
 ' Young Adult Fiction ',
 ' 63 ',
 " My Sister's Keeper ",
 ' Picoult, Jodi ',
 ' 1,003,780 ',
 ' Hodder & Stoughton ',
 ' General & Literary Fiction ',
 ' 64 ',
 ' Amber Spyglass,The:His Dark Materials S. ',
 ' Pullman, Philip ',
 ' 1,002,314 ',
 ' Scholastic Ltd. ',
 ' Young Adult Fiction ',
 ' 65 ',
 ' To Kill a Mockingbird ',
 ' Lee, Harper ',
 ' 998,213 ',
 ' Random House ',
 ' General & Literary Fiction ',
 ' 66 ',
 ' Men are from Mars, Women are from Venus:A Practical Guide for Improvin ',
 ' Gray, John ',
 ' 992,846 ',
 ' HarperCollins ',
 ' Popular Culture & Media: General Interest ',
 ' 67 ',
 ' Dear Fatty ',
 ' French, Dawn ',
 ' 986,753 ',
 ' Random House ',
 ' Autobiography: The Arts ',
 ' 68 ',
 ' Short History of Tractors in Ukrainian,A ',
 ' Lewycka, Marina ',
 ' 986,115 ',
 ' Penguin ',
 ' General & Literary Fiction ',
 ' 69 ',
 ' Hannibal ',
 ' Harris, Thomas ',
 ' 970,509 ',
 ' Random House ',
 ' Crime, Thriller & Adventure ',
 ' 70 ',
 ' Lord of the Rings,The ',
 ' Tolkien, J. R. R. ',
 ' 967,466 ',
 ' HarperCollins ',
 ' Science Fiction & Fantasy ',
 ' 71 ',
 ' Stupid White Men:...and Other Sorry Excuses for the State of the Natio ',
 ' Moore, Michael ',
 ' 963,353 ',
 ' Penguin ',
 ' Current Affairs & Issues ',
 ' 72 ',
 ' Interpretation of Murder,The ',
 ' Rubenfeld, Jed ',
 ' 962,515 ',
 ' Headline ',
 ' Crime, Thriller & Adventure ',
 ' 73 ',
 ' Sharon Osbourne Extreme:My Autobiography ',
 ' Osbourne, Sharon ',
 ' 959,496 ',
 ' Little, Brown Book ',
 ' Autobiography: The Arts ',
 ' 74 ',
 ' Alchemist,The:A Fable About Following Your Dream ',
 ' Coelho, Paulo ',
 ' 956,114 ',
 ' HarperCollins ',
 ' General & Literary Fiction ',
 ' 75 ',
 " At My Mother's Knee ...:and Other Low Joints ",
 " O'Grady, Paul ",
 ' 945,640 ',
 ' Transworld ',
 ' Autobiography: The Arts ',
 ' 76 ',
 ' Notes from a Small Island ',
 ' Bryson, Bill ',
 ' 931,312 ',
 ' Transworld ',
 ' Travel Writing ',
 ' 77 ',
 ' Return of the Naked Chef,The ',
 ' Oliver, Jamie ',
 ' 925,425 ',
 ' Penguin ',
 ' Food & Drink: General ',
 ' 78 ',
 ' Bridget Jones: The Edge of Reason ',
 ' Fielding, Helen ',
 ' 924,695 ',
 ' Pan Macmillan ',
 ' General & Literary Fiction ',
 ' 79 ',
 " Jamie's Italy ",
 ' Oliver, Jamie ',
 ' 906,968 ',
 ' Penguin ',
 ' National & Regional Cuisine ',
 ' 80 ',
 ' I Can Make You Thin ',
 ' McKenna, Paul ',
 ' 905,086 ',
 ' Transworld ',
 ' Fitness & Diet ',
 ' 81 ',
 ' Down Under ',
 ' Bryson, Bill ',
 ' 890,847 ',
 ' Transworld ',
 ' Travel Writing ',
 ' 82 ',
 ' Summons,The ',
 ' Grisham, John ',
 ' 869,671 ',
 ' Random House ',
 ' Crime, Thriller & Adventure ',
 ' 83 ',
 ' Small Island ',
 ' Levy, Andrea ',
 ' 869,659 ',
 ' Headline ',
 ' General & Literary Fiction ',
 ' 84 ',
 ' Nigella Express ',
 ' Lawson, Nigella ',
 ' 862,602 ',
 ' Random House ',
 ' Food & Drink: General ',
 ' 85 ',
 ' Brick Lane ',
 ' Ali, Monica ',
 ' 856,540 ',
 ' Transworld ',
 ' General & Literary Fiction ',
 ' 86 ',
 " Memory Keeper's Daughter,The ",
 ' Edwards, Kim ',
 ' 845,858 ',
 ' Penguin ',
 ' General & Literary Fiction ',
 ' 87 ',
 ' Room on the Broom ',
 ' Donaldson, Julia ',
 ' 842,535 ',
 ' Pan Macmillan ',
 ' Picture Books ',
 ' 88 ',
 ' About a Boy ',
 ' Hornby, Nick ',
 ' 828,215 ',
 ' Penguin ',
 ' General & Literary Fiction ',
 ' 89 ',
 ' My Booky Wook ',
 ' Brand, Russell ',
 ' 820,563 ',
 ' Hodder & Stoughton ',
 ' Autobiography: The Arts ',
 ' 90 ',
 ' God Delusion,The ',
 ' Dawkins, Richard ',
 ' 816,907 ',
 ' Transworld ',
 ' Popular Science ',
 ' 91 ',
 ' "Beano" Annual,The ',
 ' 0 ',
 ' 816,585 ',
 ' D.C. Thomson ',
 " Children's Annuals ",
 ' 92 ',
 ' White Teeth ',
 ' Smith, Zadie ',
 ' 815,586 ',
 ' Penguin ',
 ' General & Literary Fiction ',
 ' 93 ',
 ' House at Riverton,The ',
 ' Morton, Kate ',
 ' 814,370 ',
 ' Pan Macmillan ',
 ' General & Literary Fiction ',
 ' 94 ',
 ' Book Thief,The ',
 ' Zusak, Markus ',
 ' 809,641 ',
 ' Transworld ',
 ' General & Literary Fiction ',
 ' 95 ',
 ' Nights of Rain and Stars ',
 ' Binchy, Maeve ',
 ' 808,900 ',
 ' Orion ',
 ' General & Literary Fiction ',
 ' 96 ',
 ' Ghost,The ',
 ' Harris, Robert ',
 ' 807,311 ',
 ' Random House ',
 ' General & Literary Fiction ',
 ' 97 ',
 ' Happy Days with the Naked Chef ',
 ' Oliver, Jamie ',
 ' 794,201 ',
 ' Penguin ',
 ' Food & Drink: General ',
 ' 98 ',
 ' Hunger Games,The:Hunger Games Trilogy ',
 ' Collins, Suzanne ',
 ' 792,187 ',
 ' Scholastic Ltd. ',
 ' Young Adult Fiction ',
 ' 99 ',
 " Lost Boy,The:A Foster Child's Search for the Love of a Family ",
 ' Pelzer, Dave ',
 ' 791,507 ',
 ' Orion ',
 ' Biography: General ',
 ' 100 ',
 " Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours ",
 ' Oliver, Jamie ',
 ' 791,095 ',
 ' Penguin ',
 ' Food & Drink: General ']

In [38]:
b_t=[]
for i in range(1, len(titles), 6):
    b_t.append(titles[i])
b_t

[' Da Vinci Code,The ',
 ' Harry Potter and the Deathly Hallows ',
 " Harry Potter and the Philosopher's Stone ",
 ' Harry Potter and the Order of the Phoenix ',
 ' Fifty Shades of Grey ',
 ' Harry Potter and the Goblet of Fire ',
 ' Harry Potter and the Chamber of Secrets ',
 ' Harry Potter and the Prisoner of Azkaban ',
 ' Angels and Demons ',
 " Harry Potter and the Half-blood Prince:Children's Edition ",
 ' Fifty Shades Darker ',
 ' Twilight ',
 ' Girl with the Dragon Tattoo,The:Millennium Trilogy ',
 ' Fifty Shades Freed ',
 ' Lost Symbol,The ',
 ' New Moon ',
 ' Deception Point ',
 ' Eclipse ',
 ' Lovely Bones,The ',
 ' Curious Incident of the Dog in the Night-time,The ',
 ' Digital Fortress ',
 ' Short History of Nearly Everything,A ',
 ' Girl Who Played with Fire,The:Millennium Trilogy ',
 ' Breaking Dawn ',
 ' Very Hungry Caterpillar,The:The Very Hungry Caterpillar ',
 ' Gruffalo,The ',
 " Jamie's 30-Minute Meals ",
 ' Kite Runner,The ',
 ' One Day ',
 ' Thousand Splendid Suns,A ',
 " Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy ",
 " Time Traveler's Wife,The ",
 ' Atonement ',
 " Bridget Jones's Diary:A Novel ",
 ' World According to Clarkson,The ',
 " Captain Corelli's Mandolin ",
 ' Sound of Laughter,The ',
 ' Life of Pi ',
 ' Billy Connolly ',
 ' Child Called It,A ',
 " Gruffalo's Child,The ",
 " Angela's Ashes:A Memoir of a Childhood ",
 ' Birdsong ',
 ' Northern Lights:His Dark Materials S. ',
 ' Labyrinth ',
 ' Harry Potter and the Half-blood Prince ',
 ' Help,The ',
 ' Man and Boy ',
 ' Memoirs of a Geisha ',
 " No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S. ",
 ' Island,The ',
 ' PS, I Love You ',
 ' You are What You Eat:The Plan That Will Change Your Life ',
 ' Shadow of the Wind,The ',
 ' Tales of Beedle the Bard,The ',
 ' Broker,The ',
 " Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P ",
 ' Subtle Knife,The:His Dark Materials S. ',
 ' Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation ',
 " Delia's How to Cook:(Bk.1) ",
 ' Chocolat ',
 ' Boy in the Striped Pyjamas,The ',
 " My Sister's Keeper ",
 ' Amber Spyglass,The:His Dark Materials S. ',
 ' To Kill a Mockingbird ',
 ' Men are from Mars, Women are from Venus:A Practical Guide for Improvin ',
 ' Dear Fatty ',
 ' Short History of Tractors in Ukrainian,A ',
 ' Hannibal ',
 ' Lord of the Rings,The ',
 ' Stupid White Men:...and Other Sorry Excuses for the State of the Natio ',
 ' Interpretation of Murder,The ',
 ' Sharon Osbourne Extreme:My Autobiography ',
 ' Alchemist,The:A Fable About Following Your Dream ',
 " At My Mother's Knee ...:and Other Low Joints ",
 ' Notes from a Small Island ',
 ' Return of the Naked Chef,The ',
 ' Bridget Jones: The Edge of Reason ',
 " Jamie's Italy ",
 ' I Can Make You Thin ',
 ' Down Under ',
 ' Summons,The ',
 ' Small Island ',
 ' Nigella Express ',
 ' Brick Lane ',
 " Memory Keeper's Daughter,The ",
 ' Room on the Broom ',
 ' About a Boy ',
 ' My Booky Wook ',
 ' God Delusion,The ',
 ' "Beano" Annual,The ',
 ' White Teeth ',
 ' House at Riverton,The ',
 ' Book Thief,The ',
 ' Nights of Rain and Stars ',
 ' Ghost,The ',
 ' Happy Days with the Naked Chef ',
 ' Hunger Games,The:Hunger Games Trilogy ',
 " Lost Boy,The:A Foster Child's Search for the Love of a Family ",
 " Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours "]

In [41]:
a_n=[]
for i in range(2, len(titles), 6):
    a_n.append(titles[i])
a_n

[' Brown, Dan ',
 ' Rowling, J.K. ',
 ' Rowling, J.K. ',
 ' Rowling, J.K. ',
 ' James, E. L. ',
 ' Rowling, J.K. ',
 ' Rowling, J.K. ',
 ' Rowling, J.K. ',
 ' Brown, Dan ',
 ' Rowling, J.K. ',
 ' James, E. L. ',
 ' Meyer, Stephenie ',
 ' Larsson, Stieg ',
 ' James, E. L. ',
 ' Brown, Dan ',
 ' Meyer, Stephenie ',
 ' Brown, Dan ',
 ' Meyer, Stephenie ',
 ' Sebold, Alice ',
 ' Haddon, Mark ',
 ' Brown, Dan ',
 ' Bryson, Bill ',
 ' Larsson, Stieg ',
 ' Meyer, Stephenie ',
 ' Carle, Eric ',
 ' Donaldson, Julia ',
 ' Oliver, Jamie ',
 ' Hosseini, Khaled ',
 ' Nicholls, David ',
 ' Hosseini, Khaled ',
 ' Larsson, Stieg ',
 ' Niffenegger, Audrey ',
 ' McEwan, Ian ',
 ' Fielding, Helen ',
 ' Clarkson, Jeremy ',
 ' Bernieres, Louis de ',
 ' Kay, Peter ',
 ' Martel, Yann ',
 ' Stephenson, Pamela ',
 ' Pelzer, Dave ',
 ' Donaldson, Julia ',
 ' McCourt, Frank ',
 ' Faulks, Sebastian ',
 ' Pullman, Philip ',
 ' Mosse, Kate ',
 ' Rowling, J.K. ',
 ' Stockett, Kathryn ',
 ' Parsons, Tony ',
 ' Golden, Arthur ',
 ' McCall Smith, Alexander ',
 ' Hislop, Victoria ',
 ' Ahern, Cecelia ',
 ' McKeith, Gillian ',
 ' Zafon, Carlos Ruiz ',
 ' Rowling, J.K. ',
 ' Grisham, John ',
 ' Atkins, Robert C. ',
 ' Pullman, Philip ',
 ' Truss, Lynne ',
 ' Smith, Delia ',
 ' Harris, Joanne ',
 ' Boyne, John ',
 ' Picoult, Jodi ',
 ' Pullman, Philip ',
 ' Lee, Harper ',
 ' Gray, John ',
 ' French, Dawn ',
 ' Lewycka, Marina ',
 ' Harris, Thomas ',
 ' Tolkien, J. R. R. ',
 ' Moore, Michael ',
 ' Rubenfeld, Jed ',
 ' Osbourne, Sharon ',
 ' Coelho, Paulo ',
 " O'Grady, Paul ",
 ' Bryson, Bill ',
 ' Oliver, Jamie ',
 ' Fielding, Helen ',
 ' Oliver, Jamie ',
 ' McKenna, Paul ',
 ' Bryson, Bill ',
 ' Grisham, John ',
 ' Levy, Andrea ',
 ' Lawson, Nigella ',
 ' Ali, Monica ',
 ' Edwards, Kim ',
 ' Donaldson, Julia ',
 ' Hornby, Nick ',
 ' Brand, Russell ',
 ' Dawkins, Richard ',
 ' 0 ',
 ' Smith, Zadie ',
 ' Morton, Kate ',
 ' Zusak, Markus ',
 ' Binchy, Maeve ',
 ' Harris, Robert ',
 ' Oliver, Jamie ',
 ' Collins, Suzanne ',
 ' Pelzer, Dave ',
 ' Oliver, Jamie ']

In [42]:
v_s=[]
for i in range(3, len(titles), 6):
    v_s.append(titles[i])
v_s

[' 5,094,805 ',
 ' 4,475,152 ',
 ' 4,200,654 ',
 ' 4,179,479 ',
 ' 3,758,936 ',
 ' 3,583,215 ',
 ' 3,484,047 ',
 ' 3,377,906 ',
 ' 3,193,946 ',
 ' 2,950,264 ',
 ' 2,479,784 ',
 ' 2,315,405 ',
 ' 2,233,570 ',
 ' 2,193,928 ',
 ' 2,183,031 ',
 ' 2,152,737 ',
 ' 2,062,145 ',
 ' 2,052,876 ',
 ' 2,005,598 ',
 ' 1,979,552 ',
 ' 1,928,900 ',
 ' 1,852,919 ',
 ' 1,814,784 ',
 ' 1,787,118 ',
 ' 1,783,535 ',
 ' 1,781,269 ',
 ' 1,743,266 ',
 ' 1,629,119 ',
 ' 1,616,068 ',
 ' 1,583,992 ',
 ' 1,555,135 ',
 ' 1,546,886 ',
 ' 1,539,428 ',
 ' 1,508,205 ',
 ' 1,489,403 ',
 ' 1,352,318 ',
 ' 1,310,207 ',
 ' 1,310,176 ',
 ' 1,231,957 ',
 ' 1,217,712 ',
 ' 1,208,711 ',
 ' 1,204,058 ',
 ' 1,184,967 ',
 ' 1,181,503 ',
 ' 1,181,093 ',
 ' 1,153,181 ',
 ' 1,132,336 ',
 ' 1,130,802 ',
 ' 1,126,337 ',
 ' 1,115,549 ',
 ' 1,108,328 ',
 ' 1,107,379 ',
 ' 1,104,403 ',
 ' 1,092,349 ',
 ' 1,090,847 ',
 ' 1,087,262 ',
 ' 1,054,196 ',
 ' 1,037,160 ',
 ' 1,023,688 ',
 ' 1,015,956 ',
 ' 1,009,873 ',
 ' 1,004,414 ',
 ' 1,003,780 ',
 ' 1,002,314 ',
 ' 998,213 ',
 ' 992,846 ',
 ' 986,753 ',
 ' 986,115 ',
 ' 970,509 ',
 ' 967,466 ',
 ' 963,353 ',
 ' 962,515 ',
 ' 959,496 ',
 ' 956,114 ',
 ' 945,640 ',
 ' 931,312 ',
 ' 925,425 ',
 ' 924,695 ',
 ' 906,968 ',
 ' 905,086 ',
 ' 890,847 ',
 ' 869,671 ',
 ' 869,659 ',
 ' 862,602 ',
 ' 856,540 ',
 ' 845,858 ',
 ' 842,535 ',
 ' 828,215 ',
 ' 820,563 ',
 ' 816,907 ',
 ' 816,585 ',
 ' 815,586 ',
 ' 814,370 ',
 ' 809,641 ',
 ' 808,900 ',
 ' 807,311 ',
 ' 794,201 ',
 ' 792,187 ',
 ' 791,507 ',
 ' 791,095 ']

In [43]:
publ=[]
for i in range(4, len(titles), 6):
    publ.append(titles[i])
publ

[' Transworld ',
 ' Bloomsbury ',
 ' Bloomsbury ',
 ' Bloomsbury ',
 ' Random House ',
 ' Bloomsbury ',
 ' Bloomsbury ',
 ' Bloomsbury ',
 ' Transworld ',
 ' Bloomsbury ',
 ' Random House ',
 ' Little, Brown Book ',
 ' Quercus ',
 ' Random House ',
 ' Transworld ',
 ' Little, Brown Book ',
 ' Transworld ',
 ' Little, Brown Book ',
 ' Pan Macmillan ',
 ' Random House ',
 ' Transworld ',
 ' Transworld ',
 ' Quercus ',
 ' Little, Brown Book ',
 ' Penguin ',
 ' Pan Macmillan ',
 ' Penguin ',
 ' Bloomsbury ',
 ' Hodder & Stoughton ',
 ' Bloomsbury ',
 ' Quercus ',
 ' Random House ',
 ' Random House ',
 ' Pan Macmillan ',
 ' Penguin ',
 ' Random House ',
 ' Random House ',
 ' Canongate ',
 ' HarperCollins ',
 ' Orion ',
 ' Pan Macmillan ',
 ' HarperCollins ',
 ' Random House ',
 ' Scholastic Ltd. ',
 ' Orion ',
 ' Bloomsbury ',
 ' Penguin ',
 ' HarperCollins ',
 ' Random House ',
 ' Little, Brown Book ',
 ' Headline ',
 ' HarperCollins ',
 ' Penguin ',
 ' Orion ',
 ' Bloomsbury ',
 ' Random House ',
 ' Random House ',
 ' Scholastic Ltd. ',
 ' Profile Books Group ',
 ' Random House ',
 ' Transworld ',
 ' Random House Childrens Books G ',
 ' Hodder & Stoughton ',
 ' Scholastic Ltd. ',
 ' Random House ',
 ' HarperCollins ',
 ' Random House ',
 ' Penguin ',
 ' Random House ',
 ' HarperCollins ',
 ' Penguin ',
 ' Headline ',
 ' Little, Brown Book ',
 ' HarperCollins ',
 ' Transworld ',
 ' Transworld ',
 ' Penguin ',
 ' Pan Macmillan ',
 ' Penguin ',
 ' Transworld ',
 ' Transworld ',
 ' Random House ',
 ' Headline ',
 ' Random House ',
 ' Transworld ',
 ' Penguin ',
 ' Pan Macmillan ',
 ' Penguin ',
 ' Hodder & Stoughton ',
 ' Transworld ',
 ' D.C. Thomson ',
 ' Penguin ',
 ' Pan Macmillan ',
 ' Transworld ',
 ' Orion ',
 ' Random House ',
 ' Penguin ',
 ' Scholastic Ltd. ',
 ' Orion ',
 ' Penguin ']

In [45]:
genr=[]
for i in range(5, len(titles), 6):
    genr.append(titles[i])
genr

[' Crime, Thriller & Adventure ',
 " Children's Fiction ",
 " Children's Fiction ",
 " Children's Fiction ",
 ' Romance & Sagas ',
 " Children's Fiction ",
 " Children's Fiction ",
 " Children's Fiction ",
 ' Crime, Thriller & Adventure ',
 " Children's Fiction ",
 ' Romance & Sagas ',
 ' Young Adult Fiction ',
 ' Crime, Thriller & Adventure ',
 ' Romance & Sagas ',
 ' Crime, Thriller & Adventure ',
 ' Young Adult Fiction ',
 ' Crime, Thriller & Adventure ',
 ' Young Adult Fiction ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' Crime, Thriller & Adventure ',
 ' Popular Science ',
 ' Crime, Thriller & Adventure ',
 ' Young Adult Fiction ',
 ' Picture Books ',
 ' Picture Books ',
 ' Food & Drink: General ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' Crime, Thriller & Adventure ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' Humour: Collections & General ',
 ' General & Literary Fiction ',
 ' Autobiography: General ',
 ' General & Literary Fiction ',
 ' Biography: The Arts ',
 ' Autobiography: General ',
 ' Picture Books ',
 ' Autobiography: General ',
 ' General & Literary Fiction ',
 ' Young Adult Fiction ',
 ' General & Literary Fiction ',
 ' Science Fiction & Fantasy ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' Crime, Thriller & Adventure ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' Fitness & Diet ',
 ' General & Literary Fiction ',
 " Children's Fiction ",
 ' Crime, Thriller & Adventure ',
 ' Fitness & Diet ',
 ' Young Adult Fiction ',
 ' Usage & Writing Guides ',
 ' Food & Drink: General ',
 ' General & Literary Fiction ',
 ' Young Adult Fiction ',
 ' General & Literary Fiction ',
 ' Young Adult Fiction ',
 ' General & Literary Fiction ',
 ' Popular Culture & Media: General Interest ',
 ' Autobiography: The Arts ',
 ' General & Literary Fiction ',
 ' Crime, Thriller & Adventure ',
 ' Science Fiction & Fantasy ',
 ' Current Affairs & Issues ',
 ' Crime, Thriller & Adventure ',
 ' Autobiography: The Arts ',
 ' General & Literary Fiction ',
 ' Autobiography: The Arts ',
 ' Travel Writing ',
 ' Food & Drink: General ',
 ' General & Literary Fiction ',
 ' National & Regional Cuisine ',
 ' Fitness & Diet ',
 ' Travel Writing ',
 ' Crime, Thriller & Adventure ',
 ' General & Literary Fiction ',
 ' Food & Drink: General ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' Picture Books ',
 ' General & Literary Fiction ',
 ' Autobiography: The Arts ',
 ' Popular Science ',
 " Children's Annuals ",
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' General & Literary Fiction ',
 ' Food & Drink: General ',
 ' Young Adult Fiction ',
 ' Biography: General ',
 ' Food & Drink: General ']

In [47]:
print(len(genr),len(publ),len(v_s),len(a_n),len(b_t))

100 100 100 100 100

In [48]:
highest_selling_novel=pd.DataFrame({})
highest_selling_novel['Book Title']=b_t
highest_selling_novel['Author Name']=a_n
highest_selling_novel['Volume Sold']=v_s
highest_selling_novel['Publisher']=publ
highest_selling_novel['Genre']=genr
highest_selling_novel

,Book Title,Author Name,Volume Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the ...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to ...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location

In [66]:
url2='https://www.naukri.com/data-science-recruiters'
page2=requests.get(url2)
soup2=BeautifulSoup(page2.content)

In [67]:
name=soup2.find_all('span', class_="fl ellipsis")
recruiter_name=[]
for i in name:
    recruiter_name.append(i.text)
recruiter_name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and ',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Priyanka Akiri',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Ruchi Dhote',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Priya Khare',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'SREEDHAR',
 'Radha Manivasagam',
 'Prateek Kumar',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury',
 'Shailja Mishra']

In [68]:
designation=soup2.find_all('span', class_="ellipsis clr")
recruiter_designation=[]
for i in designation:
    recruiter_designation.append(i.text)
recruiter_designation

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'HR Manager',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'Senior Executive Talent Acquisition',
 'HR Team Lead',
 'HR Manager',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Senior Manager',
 'Company Recruitment Head',
 'Project Manager',
 'Recruitment Consultant',
 'HR Executive',
 'Head',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner',
 'HR Manager']

In [70]:
company=soup2.find_all('a', class_="ellipsis")
recruiter_company=[]
for i in company:
    recruiter_company.append(i.text)
recruiter_company
rec_comp=[]
for i in range(1, len(recruiter_company), 2):
    rec_comp.append(recruiter_company[i])
rec_comp

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Infinitive Software Solutions Pvt.Ltd.',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'Bristlecone India Ltd',
 'SocialPrachar.com',
 'BISP Solutions',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Independent Consultant',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED',
 'Techcovery',
 'Trisect',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai',
 'Certybox Pvt.Ltd.']

In [71]:
skills=soup2.find_all('div', class_="hireSec highlightable")
recruiter_skills=[]
for i in skills:
    recruiter_skills.append(i.text)
recruiter_skills

['    Classic ASP Developer,   Internet Marketing Professional,   Data Science SME,   Content Writers,   SEO Professional,   Revenue Professional    ',
 '    .Net,   Java,   Data Science,   Linux Administration,   Sql Server Development,   Winforms,   Wcf Services,   Wpf,   Telecom Engineering,   Technical Management,   Software    ',
 '    Data Science,   Artificial Intelligence,   Machine Learning,   Business Analytics    ',
 '    Mean Stack,   javascript,   angularjs,   mongodb,   Web Services,   rest,   express,   Node.js,   Big Data,   iot,   Data Science,   Cloud Computing,   saas,   Aws    ',
 '    Hadoop,   Spark,   Digital Strategy,   Data Architecture,   Command Center,   Cdp,   Dmp,   Kafka,   Data Science,   Data Analysis,   Big Data Analytics,   Real Time Analysis,   SQL    ',
 '    Analytics,   Business Intelligence,   Business Analytics,   Predictive Modeling,   Predictive Analytics,   Data Science,   Data Analysis,   Data Analytics,   Big Data,   Big    ',
 '    Data Science    ',
 '    Machine Learning,   algorithms,   Go Getter,   Computer Science,   spark,   Big Data,   hdfs,   sql,   cassandra,   hadoop,   python,   scala,   java,   Data Science,   Front End    ',
 '    Technical Training,   Software Development,   Presentation Skills,   B.tech,   M.tech,   B.e.,   mca,   msc,   Computer Science,   freshers,   jobs in indore,   Data Science,   itil    ',
 '    Software Development,   It Sales,   Account Management,   Data Analysis,   Customer Service,   Sr,   Software Engineering,   Mvc,   Ajax,   Asp.net,   Html,   C#,   Javascript    ',
 '    Oracle Dba,   Data Science,   Data Warehousing,   ETL,   Jupyter,   Numpy,   Data Transformation,   Snowflake,   Teradata,   Python,   Data Manipulation,   Relational Databases    ',
 '    Qa,   Ui/ux,   Java Developer,   Java Architect,   C++/qt,   Php,   Lamp,   Api,   J2ee,   Java,   Soa,   Esb,   Middleware,   Bigdata Achitect,   Hadoop Architect,   Deep    ',
 '    Business Intelligence,   Data Warehousing,   Data Science,   Business Analytics,   Customer Support,   Business Reporting,   Bi    ',
 '    Office Administration,   Hr Administration,   telecalling,   client relationship management,   Client Acquisition,   Sales,   Reception,   HR,   Recruitment,   Onboarding,   Human    ',
 '    Qlikview,   Qlik Sense,   Microsoft Azure,   Power Bi,   Data Science,   Machine Learning    ',
 '    Social Media,   digital media maketing,   seo,   smm,   smo,   sem,   Content Wirting,   social media marketing,   social media manager,   digital media marketing manager    ',
 '    Big Data,   Hadoop,   Data Analytics,   Data Science    ',
 '    Telecalling,   Client Interaction,   Marketing,   Research,   Web Development,   Social Media Marketing,   Data Entry Operation,   Excel,   Ms Office,   Invoicing    ',
 '    Data Science    ',
 '    Corporate Sales,   Software Development,   Software Sales,   Marketing,   Creative Designing,   Corporate Planning,   Senior Management,   Crm,   Client Relationship    ',
 '    Data Analytics,   Data Science,   Machine Learning,   Deep Learning,   Nlp,   Data Mining,   Python,   R,   Database Administration,   Text Mining    ',
 '    Data Science,   Machine Learning,   Python,   R,   Deep Learning,   Big Data,   Hadoop    ',
 '    Big Data,   Data Science,   Artificial Intelligence,   Hadoop,   Ui Development,   Php,   Freelancing,   .Net,   Software Testing,   Sap,   Leadership Hiring    ',
 '    Java,   Net,   Angularjs,   Hr,   Infrastructure,   Management,   Project Management,   Business Analysis,   Data Science,   Information Technology,   Technology    ',
 '    Data Science,   Artificial Intelligence,   Machine Learning,   Data Analytics    ',
 '    Software Architecture,   Vp Engineering,   Product Management,   analytics,   Data Science,   Node.js,   Principal Engineer,   Big Data,   python,   angularjs,   React.js    ',
 '    Data Science,   Hadoop,   Rpas,   Devops,   Python,   Aws,   Teaching,   Big Data    ',
 '    Signal Processing,   Machine Learning,   Neural Networks,   Data Science,   Predictive Analytics,   Time Series Analysis,   Data Visualization,   Technical Leadership,   Data    ',
 '    Web Technologies,   Project Management,   Software Architecture,   Data Science,   Object Oriented Programming,   Computer Science,   Electrical Engineering,   Architecture    ',
 '    Data Science,   Artificial Intelligence,   analytics,   Business Intelligence,   python,   tableau,   Power Bi,   qlikview,   sql,   Data Warehousing,   Data Visualization    ',
 '    Server Administartion,   Verilog,   Vhdl,   Digital Marketing,   Market Research,   Property Research,   Legal,   It And Non It Recruitment,   Logistics,   Supply Chain,   Bfsi    ',
 '    Data Analytics,   Managed Services,   Team Leading,   python,   Machine Learning,   Google Analytics,   Dmp,   Aws,   Campaign Analytics,   Digital Campaigns,   Audience    ',
 '    Data Science,   Machine Learning,   Big Data Analytics,   Spark,   Python,   R,   Networking,   Network Engineering,   Placement,   Training,   Sql,   Marketing,   Mainframes,   All    ',
 '    Python,   Artificial Intelligence,   Machine Learning,   Data Science    ',
 '    Java,   Python,   Angularjs,   Software Testing,   Machine Learning,   Data Science,   Javascript,   Django,   React.js,   Node.js,   Augmented Reality,   Virtual Reality,   Advanced    ',
 '    Machine Learning,   Artificial Intelligence,   Data Science,   Software Engineering,   Software Development,   Graduate Engineer Trainee,   Fresher,   Data Analytics,   Java    ',
 '    C,   C++,   Artificial Intelligence,   Python,   Php,   Web Development,   Matlab,   Data Science,   Augmented Reality,   C C++    ',
 '    Relationship Management,   Retail Sales,   Private Banking,   Mutual Funds,   NISM,   Equity,   Finance,   Financial Products,   Financial Services,   Verbal,   Written    ',
 '    Data Science,   Software Engineering    ',
 '    Data Science,   Big Data Analytics,   Digital Marketing,   Content Writing,   Ui Development,   Database Development,   Qa Automation,   Python,   Project Management    ',
 '    Data Science,   Recruitment,   Salary    ',
 '    B.Tech,   Tableau,   Statistics,   R,   Analytics,   Time Series,   Data Science,   Business Solutions,   SQL,   Technical Skills,   SSAS,   SQL Server,   Analysis Services,   Qlikview    ',
 '    Software Development,   Business Intelligence,   Big Data Analytics,   Database Administration,   Data Science,   Microsoft Azure,   Spark,   Cassandra,   Object Oriented    ',
 '    Data Science,   Node.js,   Angularjs    ',
 '    Data Science,   Media Marketing,   Resource Planning,   Managed Services,   Display Advertising,   Machine Learning,   Python,   Etl,   Sql    ',
 '    Data Analysis,   Learning,   Data Science,   Computer Science,   Communication Skills    ',
 '    Java,   Hadoop,   R,   Machine Learning,   Spark,   Flume,   Hdfs,   Data Mining,   Sas,   Big,   Data Science,   Cloudera,   Impala,   Bigdata    ',
 '    Software Development,   Core Java,   Unit Testing,   Customer Experience,   Problem Solving,   Communication Skills,   Mysql,   Data Science,   Sales Management,   Analytics    ',
 '    Machine Learning,   Data Science,   Product Management,   New Product,   Data Analysis,   Computer Vision,   Deep Learning,   Python,   Remote Sensing    ',
 '    consulting,   Education Counseling,   Educational Sales,   Institutional Sales,   pmp,   Data Science,   Business Development,   Revenue Generation,   Sales Achievement,   new    ']

In [79]:
location=soup2.find_all('small', class_="ellipsis")
recruiter_location=[]
for i in location:
    recruiter_location.append(i.text)
recruiter_location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Pune',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Noida',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Noida']

In [82]:
recruiter_location.append("Delhi")

In [83]:
print(len(recruiter_name),len(recruiter_designation),len(rec_comp),len(recruiter_skills),len(recruiter_location))

50 50 50 50 50

In [84]:
data_sci_recruiter=pd.DataFrame({})
data_sci_recruiter['Name']=recruiter_name
data_sci_recruiter['Designation']=recruiter_designation
data_sci_recruiter['Company']=rec_comp
data_sci_recruiter['Skills']=recruiter_skills
data_sci_recruiter['Location']=recruiter_location
data_sci_recruiter

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketin...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Admi...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, ...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, m...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Dat...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Busi...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Gette...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Accoun...",Bengaluru / Bangalore
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,"Oracle Dba, Data Science, Data Warehou...",Hyderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Arch...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing,...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration...",Mumbai
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure,...",Pune
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, ...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Da...",Bhopal
17,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marke...",Navi Mumbai
18,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
19,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, ...",Delhi
20,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine ...",Hyderabad / Secunderabad
21,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python...",Pune
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Int...",Pune
23,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastr...",Pune
24,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, ...",Pune
25,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, ...",Bengaluru / Bangalore
26,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, ...",Bengaluru / Bangalore
27,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, N...",Delhi
28,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, ...",Bengaluru / Bangalore
29,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, ...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, ...",Mysoru / Mysore
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team...",Hyderabad / Secunderabad
32,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Da...",Bengaluru / Bangalore
33,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machi...",Noida
34,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Te...",New Delhi
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligenc...",Chennai
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Pyt...",Aligarh
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, ...",Salt Lake City
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digi...",Bengaluru / Bangalore
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, An...",Indore
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intellige...",Bengaluru / Bangalore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resourc...",Hyderabad / Secunderabad
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science,...",Bengaluru / Bangalore
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, ...",Mumbai
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit ...",Noida
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Produc...","[Delhi, Chennai]"
49,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educ...",Delhi

6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [116]:
url3='https://www.billboard.com/charts/hot-100'
page3=requests.get(url3)
soup3=BeautifulSoup(page3.content)

In [117]:
song_name=soup3.find_all('span', class_="chart-element__information__song text--truncate color--primary")
s_n=[]
for i in song_name:
    s_n.append(i.text)
s_n

['Stay',
 'Bad Habits',
 'Good 4 U',
 'Kiss Me More',
 'Industry Baby',
 'Levitating',
 'Butter',
 'Deja Vu',
 'Montero (Call Me By Your Name)',
 'Save Your Tears',
 'Fancy Like',
 'You Right',
 'Essence',
 'Need To Know',
 'Leave The Door Open',
 'Take My Breath',
 'Rumors',
 'Peaches',
 'Heartbreak Anniversary',
 'Blinding Lights',
 'Leave Before You Love Me',
 'Happier Than Ever',
 'Forever After All',
 'Waves',
 'Every Chance I Get',
 'Pepas',
 'Thot Shit',
 'Traitor',
 "Beggin'",
 'Arcade',
 'Late At Night',
 'Things A Man Oughta Know',
 'Heat Waves',
 'Chasing After You',
 'Wockesha',
 'Glad You Exist',
 'Without You',
 'Skate',
 'Astronaut In The Ocean',
 'Rapstar',
 "We Didn't Have Much",
 'Country Again',
 'Famous Friends',
 "If I Didn't Love You",
 'Cold Beer Calling My Name',
 'Lil Bit',
 'Beautiful Mistakes',
 'Summer Of Love',
 'Matt Hardy 999',
 'Whole Lotta Money',
 '2055',
 'A-O-K',
 "Drinkin' Beer. Talkin' God. Amen.",
 'Love Again',
 'Volvi',
 'Rich MF',
 'Todo de Ti',
 'Yonaguni',
 'Wild Side',
 'Already Won',
 'Single Saturday Night',
 "Drunk (And I Don't Wanna Go Home)",
 'I Was On A Boat That Day',
 'Motley Crew',
 "Ain't Shit",
 'Memory',
 'Betrayal',
 'Get Into It (Yuh)',
 "Don't Go",
 'Woman',
 "Don't Go Yet",
 'Tombstone',
 'One Mississippi',
 'Gyalis',
 'Visiting Hours',
 'You Should Probably Leave',
 "Memory I Don't Mess With",
 'Holy Smokes',
 'Miss The Rage',
 'Cold As You',
 'My Boy',
 'You',
 'Come Through',
 'Buy Dirt',
 'You Time',
 'MP5',
 'Paralyzed',
 'Baddest',
 'Brutal',
 "I Guess I'm In Love",
 'Get Ready',
 'Danny Phantom',
 "What's Wrong",
 'Demon Time',
 'Knowing You',
 'Tick Tock',
 'Permission To Dance',
 'AM',
 'Time Heals',
 "Thinking 'Bout You"]

In [118]:
artist_name=soup3.find_all('span', class_="chart-element__information__artist text--truncate color--secondary")
a_n=[]
for i in artist_name:
    a_n.append(i.text)
a_n

['The Kid LAROI & Justin Bieber',
 'Ed Sheeran',
 'Olivia Rodrigo',
 'Doja Cat Featuring SZA',
 'Lil Nas X & Jack Harlow',
 'Dua Lipa',
 'BTS',
 'Olivia Rodrigo',
 'Lil Nas X',
 'The Weeknd & Ariana Grande',
 'Walker Hayes',
 'Doja Cat & The Weeknd',
 'Wizkid Featuring Justin Bieber & Tems',
 'Doja Cat',
 'Silk Sonic (Bruno Mars & Anderson .Paak)',
 'The Weeknd',
 'Lizzo Featuring Cardi B',
 'Justin Bieber Featuring Daniel Caesar & Giveon',
 'Giveon',
 'The Weeknd',
 'Marshmello X Jonas Brothers',
 'Billie Eilish',
 'Luke Combs',
 'Luke Bryan',
 'DJ Khaled Featuring Lil Baby & Lil Durk',
 'Farruko',
 'Megan Thee Stallion',
 'Olivia Rodrigo',
 'Maneskin',
 'Duncan Laurence',
 'Roddy Ricch',
 'Lainey Wilson',
 'Glass Animals',
 'Ryan Hurd With Maren Morris',
 'Moneybagg Yo',
 'Dan + Shay',
 'The Kid LAROI',
 'Silk Sonic (Bruno Mars & Anderson .Paak)',
 'Masked Wolf',
 'Polo G',
 'Justin Moore',
 'Thomas Rhett',
 'Chris Young + Kane Brown',
 'Jason Aldean & Carrie Underwood',
 'Jameson Rodgers Featuring Luke Combs',
 'Nelly & Florida Georgia Line',
 'Maroon 5 Featuring Megan Thee Stallion',
 'Shawn Mendes & Tainy',
 'Trippie Redd Featuring Juice WRLD',
 'BIA Featuring Nicki Minaj',
 'Sleepy Hallow',
 'Tai Verdes',
 'Chase Rice Featuring Florida Georgia Line',
 'Dua Lipa',
 'Aventura x Bad Bunny',
 'Trippie Redd Featuring Lil Durk & Polo G',
 'Rauw Alejandro',
 'Bad Bunny',
 'Normani Featuring Cardi B',
 'Rod Wave Featuring Lil Durk',
 'Cole Swindell',
 'Elle King & Miranda Lambert',
 'Old Dominion',
 'Post Malone',
 'Doja Cat',
 'Kane Brown X blackbear',
 'Trippie Redd Featuring Drake',
 'Doja Cat',
 'Skrillex, Justin Bieber & Don Toliver',
 'Doja Cat',
 'Camila Cabello',
 'Rod Wave',
 'Kane Brown',
 'Capella Grey',
 'Ed Sheeran',
 'Chris Stapleton',
 'Lee Brice',
 'Trippie Redd Featuring Lil Uzi Vert',
 'Trippie Redd & Playboi Carti',
 'Luke Combs',
 'Elvie Shane',
 'Regard x Troye Sivan x Tate McRae',
 'H.E.R. Featuring Chris Brown',
 'Jordan Davis Featuring Luke Bryan',
 'Scotty McCreery',
 'Trippie Redd Featuring SoFaygo',
 'Sueco',
 'Yung Bleu, Chris Brown & 2 Chainz',
 'Olivia Rodrigo',
 'Clinton Kane',
 'Rod Wave Featuring Kodak Black',
 'Trippie Redd Featuring XXXTENTACION',
 'Rod Wave',
 'Trippie Redd Featuring Ski Mask The Slump God',
 'Kenny Chesney',
 'Young Thug',
 'BTS',
 'Nio Garcia X J Balvin X Bad Bunny',
 'Rod Wave',
 'Dustin Lynch Featuring Lauren Alaina Or MacKenzie Porter']

In [121]:
week_rank=soup3.find_all('div', class_="chart-element__meta text--center color--secondary text--last")
w_r=[]
for i in week_rank:
    w_r.append(i.text)
w_r

[]

In [122]:
peak_rank=soup3.find_all('div', class_="chart-element__meta text--center color--secondary text--peak")
p_r=[]
for i in peak_rank:
    p_r.append(i.text)
p_r

[]

In [124]:
week_board=soup3.find_all('div', class_="chart-element__meta text--center color--secondary text--week")
w_b=[]
for i in week_board:
    w_b.append(i.text)
w_b

[]

5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [125]:
url4='https://github.com/trending'
page4=requests.get(url4)
soup4=BeautifulSoup(page4.content)

In [127]:
repos_name=soup4.find_all('h1', class_="h3 lh-condensed")
r_n=[]
for i in repos_name:
    r_n.append(i.text.replace('\n',''))
r_n

['        bespoyasov /      frontend-clean-architecture ',
 '        TheAlgorithms /      Python ',
 '        bpierre /      loot-rarity ',
 '        HashLips /      generative-art-opensource ',
 '        microsoft /      PowerToys ',
 '        Anuken /      Mindustry ',
 '        TheAlgorithms /      Javascript ',
 '        30-seconds /      30-seconds-of-code ',
 '        orhun /      git-cliff ',
 '        alexeygrigorev /      mlbookcamp-code ',
 '        ABZ-Aaron /      CheatSheets ',
 '        vxunderground /      MalwareSourceCode ',
 '        andrecronje /      rarity ',
 '        wangdoc /      clang-tutorial ',
 '        HXSecurity /      DongTai ',
 '        freefq /      free ',
 '        g-make-it /      IG_Trading_Algo_Scripts_Python ',
 '        DayBreak-u /      chineseocr_lite ',
 '        girlscript /      winter-of-contributing ',
 '        streamich /      react-use ',
 '        khanhas /      spicetify-cli ',
 '        VickScarlet /      lifeRestart ',
 '        0voice /      Introduction-to-Golang ',
 '        Vonng /      ddia ',
 '        LXYan2333 /      Fabric-Bedrock-Miner ']

In [129]:
repos_desc=soup4.find_all('p', class_="col-9 color-text-secondary my-1 pr-4")
r_d=[]
for i in repos_desc:
    r_d.append(i.text.replace('\n',''))
r_d

['      React + TypeScript app built using clean architecture principles.    ',
 '      All Algorithms implemented in Python    ',
 '🤍 💚 💙 💜 🧡 ❤️ Rarity levels for Loot.    ',
 '      Create generative art by using the canvas api and node js, feel free to contribute to this repo with new ideas.    ',
 '      Windows system utilities to maximize productivity    ',
 '      A sandbox tower defense game    ',
 '      A repository for All algorithms implemented in Javascript (for educational purposes only)    ',
 '      Short JavaScript code snippets for all your development needs    ',
 '      A highly customizable Changelog Generator that follows Conventional Commit specifications ⛰️',
 '      The code from the Machine Learning Bookcamp book    ',
 '      Just a place to store cheatsheets    ',
 '      Collection of malware source code for a variety of platforms in an array of different programming languages.    ',
 '      d20srd reference implementation codified in solidity    ',
 '      C 语言教程    ',
 '      DongTai is an interactive application security testing(IAST) product that supports the detection of OWASP WEB TOP 10 vulnerabilities, multi-request related vulnerabilities (including logic vulnerabilities, unauthorized access vulnerabilities, etc.), third-party component vulnerabilities, etc.    ',
 '      翻墙、免费翻墙、免费科学上网、免费节点、免费梯子、免费ss/v2ray/trojan节点、蓝灯、谷歌商店、翻墙梯子    ',
 '      IG Trading Algos and Scripts in Python    ',
 '      超轻量级中文ocr，支持竖排文字识别, 支持ncnn、mnn、tnn推理 ( dbnet(1.8M) + crnn(2.5M) + anglenet(378KB)) 总模型仅4.7M     ',
 "      GirlScript Winter of Contributing, a three-month enthusiastic program organized by🧡GirlScript Foundation to create the world's largest multilingual content repository that will be available to everyone.     ",
 '      React Hooks — 👍',
 '      Commandline tool to customize Spotify client. Supports Windows, MacOS and Linux.    ',
 '      やり直すんだ。そして、次はうまくやる。    ',
 '      【未来服务器端编程语言】最全空降golang资料补给包（满血战斗），包含文章，书籍，作者论文，理论分析，开源框架，云原生，大佬视频，大厂实战分享ppt    ',
 '      《Designing Data-Intensive Application》DDIA中文翻译    ',
 '      A fabric client mod to mine bedrock!    ']

In [136]:
contri_count=soup4.find_all('ul', class_="Counter") 
c_c=[]
for i in contri_count:
    c_c.append(i.text)
c_c

[]

In [138]:
lang_used=soup4.find_all('span', class_="d-inline-block ml-0 mr-3") 
l_n=[]
for i in lang_used:
    l_n.append(i.text.replace('\n',''))
l_n

['TypeScript',
 'Python',
 'TypeScript',
 'JavaScript',
 'C#',
 'Java',
 'JavaScript',
 'JavaScript',
 'Rust',
 'Jupyter Notebook',
 'Assembly',
 'Solidity',
 'Shell',
 'Python',
 'C++',
 'TypeScript',
 'JavaScript',
 'JavaScript',
 'Python',
 'Java']

In [148]:
l_n.append('Java')

In [149]:
print(len(r_n),len(r_d),len(l_n))

25 25 25

In [150]:
trending_repositeries=pd.DataFrame({})
trending_repositeries['Repository Name']=r_n
trending_repositeries['Repository Description']=r_d
trending_repositeries['Language Used']=l_n
trending_repositeries

,Repository Name,Repository Description,Language Used
0,bespoyasov / frontend-clean-archi...,React + TypeScript app built using clean...,TypeScript
1,TheAlgorithms / Python,All Algorithms implemented in Python,Python
2,bpierre / loot-rarity,🤍 💚 💙 💜 🧡 ❤️ Rarity levels for Loot.,TypeScript
3,HashLips / generative-art-opensou...,Create generative art by using the canva...,JavaScript
4,microsoft / PowerToys,Windows system utilities to maximize pro...,C#
5,Anuken / Mindustry,A sandbox tower defense game,Java
6,TheAlgorithms / Javascript,A repository for All algorithms implemen...,JavaScript
7,30-seconds / 30-seconds-of-code,Short JavaScript code snippets for all y...,JavaScript
8,orhun / git-cliff,A highly customizable Changelog Generato...,Rust
9,alexeygrigorev / mlbookcamp-code,The code from the Machine Learning Bookc...,Jupyter Notebook
10,ABZ-Aaron / CheatSheets,Just a place to store cheatsheets,Assembly
11,vxunderground / MalwareSourceCode,Collection of malware source code for a ...,Solidity
12,andrecronje / rarity,d20srd reference implementation codified...,Shell
13,wangdoc / clang-tutorial,C 语言教程,Python
14,HXSecurity / DongTai,DongTai is an interactive application se...,C++
15,freefq / free,翻墙、免费翻墙、免费科学上网、免费节点、免费梯子、免费ss/v2ray/troj...,TypeScript
16,g-make-it / IG_Trading_Algo_Scrip...,IG Trading Algos and Scripts in Python,JavaScript
17,DayBreak-u / chineseocr_lite,"超轻量级中文ocr，支持竖排文字识别, 支持ncnn、mnn、tnn推理 ( d...",JavaScript
18,girlscript / winter-of-contributing,"GirlScript Winter of Contributing, a thr...",Python
19,streamich / react-use,React Hooks — 👍,Java
20,khanhas / spicetify-cli,Commandline tool to customize Spotify cl...,Java
21,VickScarlet / lifeRestart,やり直すんだ。そして、次はうまくやる。,Java
22,0voice / Introduction-to-Golang,【未来服务器端编程语言】最全空降golang资料补给包（满血战斗），包含文章，书...,Java
23,Vonng / ddia,《Designing Data-Intensive Application》DD...,Java
24,LXYan2333 / Fabric-Bedrock-Miner,A fabric client mod to mine bedrock!,Java